// Edge function: inject page-specific OG / SEO meta tags for all ABAWI routes.
//
// Strategy:
//  - Static tool pages → STATIC map (exact title + SEO description)
//  - /news/:slug       → Supabase fetch (real article title, su subtitle, cover_url)
//  - /maxavis/:id      → Supabase fetch (real survey title + description)
//  - /digital/*        → slug-to-readable + category meta
//  - /academy/*        → slug-to-readable + category meta
//  - /podcasts/*       → slug-to-readable + category meta
//  - /store/*          → category fallback
//  - /boutique-sante/* → category fallback
//  - OG image          → Netlify CDN converts SVG → JPEG (WhatsApp ≤300KB limit)

const OG_IMAGE_PNG = '/abawi-og-banner.webp'  // site-wide fallback (WebP ~49K vs PNG 469K)

// Per-route OG banner images (1200×630, generated by scripts/generate-og.mjs)
const ROUTE_IMAGE = {
  '/':                          '/og/home.webp',
  '/pure':                      '/og/pure.webp',
  '/news':                      '/og/news.webp',
  '/digital':                   '/og/digital.webp',
  '/digital/pack/abawi-plus':   '/og/plans.webp',
  '/academy':                   '/og/academy.webp',
  '/store':                     '/og/store.webp',
  '/boutique-sante':            '/og/boutique-sante.webp',
  '/plans':                     '/og/plans.webp',
  '/podcasts':                  '/og/podcasts.webp',
  '/a-propos':                  '/og/a-propos.webp',
  '/outils':                    '/og/outils.webp',
  '/outils/cv':                 '/og/cv.webp',
  '/outils/lettre':             '/og/lettre.webp',
  '/outils/business-plan':      '/og/business-plan.webp',
  '/outils/pitch':              '/og/pitch.webp',
  '/outils/facture':            '/og/facture.webp',
  '/outils/analyse-cv':         '/og/analyse-cv.webp',
  '/outils/finance':            '/og/finance.webp',
  '/outils/juridique':          '/og/juridique.webp',
  '/outils/comptable':          '/og/comptable.webp',
  '/outils/rh':                 '/og/rh.webp',
  '/outils/immobilier':         '/og/immobilier.webp',
  '/outils/consultant':         '/og/consultant.webp',
  '/outils/infographie-pro':    '/og/infographie-pro.webp',
  '/outils/photo-studio-pro':   '/og/photo-studio-pro.webp',
  '/outils/audio-studio-elite': '/og/audio-studio-elite.webp',
  '/outils/studio-visuel-pro':  '/og/studio-visuel-pro.webp',
  '/outils/image-pro':          '/og/image-pro.webp',
  '/outils/qr-code-pro':        '/og/qr-code-pro.webp',
  '/outils/pro-card-elite':     '/og/pro-card-elite.webp',
  '/outils/format-converter':   '/og/format-converter.webp',
  '/outils/dictionnaire-elite': '/og/dictionnaire-elite.webp',
  '/outils/translator-elite':   '/og/translator-elite.webp',
  '/outils/abawi-ia':           '/og/abawi-ia.webp',
  '/outils/exegetika':          '/og/exegetika.webp',
  '/outils/sante':              '/og/sante.webp',
  '/abavie':                    '/og/abavie.webp',
  '/outils/abspacegps':         '/og/abspacegps.webp',
  '/outils/abzone':             '/og/abzone.webp',
  '/outils/maxavis':            '/og/maxavis.webp',
  '/outils/tontine':            '/og/tontine.webp',
  '/outils/autoroute':          '/og/autoroute.webp',
  '/outils/editeur-pro':        '/og/editeur-pro.webp',
  '/outils/smart-word-editor':  '/og/smart-word-editor.webp',
  '/outils/smart-office':       '/og/smart-office.webp',
  '/outils/recrute-moi-sn':     '/og/recrute-moi-sn.webp',
  '/outils/place-ouvrier':      '/og/place-ouvrier.webp',
  '/outils/espace-ouvrier':     '/og/espace-ouvrier.webp',
  '/abawi360':                  '/og/abawi360.webp',
  '/abawi360/crm':              '/og/abawi360-crm.webp',
  '/abawi360/planification':    '/og/abawi360-planif.webp',
  '/abawi360/statistiques':     '/og/abawi360-stats.webp',
  '/abawi360/marketing':        '/og/abawi360-mktg.webp',
  '/abawi-pay':                 '/og/abawi-pay.webp',
  '/abawi-bank':                '/og/abawi-bank.webp',
  '/arkel-up-center':           '/og/arkel-up-center.webp',
  '/abtalk':                    '/og/abtalk.webp',
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function slugify(str) {
  return String(str ?? '')
    .toLowerCase()
    .normalize('NFD').replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

// Articles store `ti` sometimes JSON-encoded. Unwrap like ArticleDetail.jsx.
function unwrapTitle(raw) {
  let val = raw
  for (let i = 0; i < 4; i++) {
    if (typeof val !== 'string') return String(val ?? '')
    try {
      const p = JSON.parse(val)
      if (p && typeof p === 'object') val = p.ti ?? p.su ?? val
      else break
    } catch { break }
  }
  return String(val ?? '')
}

function slugToReadable(slug) {
  return String(slug ?? '')
    .split('-')
    .map(w => w ? w[0].toUpperCase() + w.slice(1) : '')
    .join(' ')
    .trim()
}

function esc(str) {
  return String(str ?? '')
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}

// ─── Supabase helpers ─────────────────────────────────────────────────────────

// [context.production.environment] sets SUPABASE_URL/SUPABASE_ANON_KEY (runtime).
// VITE_ variants are build-time only → used as local-dev fallback.
function sbUrl()  { return Deno.env.get('SUPABASE_URL')  ?? Deno.env.get('VITE_SUPABASE_URL')  ?? '' }
function sbKey()  { return Deno.env.get('SUPABASE_ANON_KEY') ?? Deno.env.get('VITE_SUPABASE_ANON_KEY') ?? '' }
function sbHeaders() {
  const k = sbKey()
  return { apikey: k, Authorization: `Bearer ${k}` }
}

// Fetch article by slug (matches ArticleDetail.jsx slug logic).
async function fetchNewsMeta(slug) {
  const base = sbUrl()
  if (!base) return null
  try {
    const res = await fetch(
      `${base}/rest/v1/articles?select=ti,su,cover_url,tag&limit=600`,
      { headers: sbHeaders() }
    )
    if (!res.ok) return null
    const rows = await res.json()
    const found = rows.find(a => {
      const clean = unwrapTitle(a.ti)
      return slugify(clean) === slug || slugify(a.ti) === slug
    })
    if (!found) return null
    const title = unwrapTitle(found.ti).slice(0, 90)
    const tag   = found.tag || 'Actualité'
    const desc  = found.su
      ? String(found.su).replace(/<[^>]+>/g, '').slice(0, 200)
      : `${tag} · Actualités économiques et business pour l'Afrique — ABAWI`
    return {
      title: `${title} — ABAWI`,
      desc,
      image: found.cover_url || null,
      type:  'article',
    }
  } catch { return null }
}

// Fetch MaxAvis survey title + description.
async function fetchMaxAvisMeta(surveyId) {
  const base = sbUrl()
  if (!base) return null
  try {
    const res = await fetch(
      `${base}/rest/v1/maxavis_surveys?select=title,description&id=eq.${encodeURIComponent(surveyId)}&limit=1`,
      { headers: sbHeaders() }
    )
    if (!res.ok) return null
    const rows = await res.json()
    const row  = rows[0]
    if (!row) return null
    return {
      title: `${String(row.title).slice(0, 80)} — Sondage ABAWI`,
      desc:  row.description
        ? String(row.description).slice(0, 200)
        : 'Participez à ce sondage ABAWI et donnez votre avis en quelques clics.',
    }
  } catch { return null }
}

// ─── Dynamic route resolvers ──────────────────────────────────────────────────

function resolveGuideMeta(slug) {
  const r = slugToReadable(slug)
  return {
    title: `${r} — Guide Premium ABAWI Digital`,
    desc:  `Guide business premium ABAWI : "${r}". Développez vos compétences entrepreneuriales et votre activité en Afrique de l'Ouest.`,
  }
}

function resolvePackMeta(slug) {
  const r = slugToReadable(slug)
  return {
    title: `Pack ${r} — ABAWI Digital`,
    desc:  `Pack de guides premium ABAWI : ${r}. Accédez à plusieurs ressources business à tarif réduit pour entrepreneurs africains.`,
  }
}

function resolveAcademyMeta(slug) {
  const r = slugToReadable(slug)
  return {
    title: `${r} — Fascicule ABAWI Académie`,
    desc:  `Fascicule de révision ABAWI : "${r}". Préparez votre Bac et vos concours avec les meilleures ressources sénégalaises.`,
  }
}

function resolvePodcastMeta(slug) {
  const r = slugToReadable(slug)
  return {
    title: `${r} — Podcast ABAWI`,
    desc:  `Écoutez "${r}" sur ABAWI Podcasts : insights business, stratégie et entrepreneuriat pour l'Afrique de l'Ouest.`,
  }
}

function resolveStoreMeta() {
  return {
    title: 'ABAWI Store — Ressources & Matériel Professionnel',
    desc:  'Découvrez nos ressources et produits professionnels ABAWI : templates, guides, matériel IT — qualité premium pour entrepreneurs africains.',
  }
}

function resolveSanteMeta() {
  return {
    title: 'Boutique Santé Abavie — ABAWI',
    desc:  'Matériel médical et tenues professionnelles de santé disponibles au Sénégal. Commandez facilement sur Abavie par ABAWI.',
  }
}

// ─── Static meta map ─────────────────────────────────────────────────────────

const STATIC = {

  // ── Racine & navigation ──────────────────────────────────────────────────
  '/': {
    title: 'ABAWI — Guides Premium, Outils IA et Académie Business pour l\'Afrique',
    desc:  'Portail premium africain : guides business, outils IA (CV, factures, finance, juridique), académie Bac. Dakar, Sénégal.',
  },

  // ── Pages principales ─────────────────────────────────────────────────────
  '/news': {
    title: 'Actualités Économiques Afrique — ABAWI',
    desc:  'Toute l\'actualité économique, business et technologique pour l\'Afrique de l\'Ouest : analyses, tendances et opportunités.',
  },
  '/digital': {
    title: 'Guides Premium ABAWI — Business & Entrepreneuriat Afrique',
    desc:  'Guides business premium pour l\'Afrique : entrepreneuriat, finance SYSCOHADA, marketing, droit OHADA et bien plus.',
  },
  '/digital/pack/abawi-plus': {
    title: 'ABAWI+ — Accès Illimité à Tous les Guides Premium',
    desc:  'Abonnement ABAWI+ : accédez à 100+ guides business, outils IA illimités et ressources académiques pour entrepreneurs africains.',
  },
  '/academy': {
    title: 'Académie ABAWI — Préparation Bac & Cours Sénégal',
    desc:  'Révisez votre Bac avec les meilleurs fascicules ABAWI : maths, sciences, français, anglais — adapté au programme sénégalais.',
  },
  '/podcasts': {
    title: 'Podcasts ABAWI — Business & Entrepreneuriat en Afrique',
    desc:  'Écoutez les meilleurs podcasts business africains : stratégie, finance, marketing, success stories d\'entrepreneurs sénégalais.',
  },
  '/store': {
    title: 'ABAWI Store — Produits & Ressources Professionnelles',
    desc:  'Boutique ABAWI : templates, guides, formations et ressources business premium pour entrepreneurs africains.',
  },
  '/boutique-sante': {
    title: 'Boutique Santé Abavie — Matériel Médical Sénégal',
    desc:  'Commandez du matériel médical et des tenues professionnelles de santé au Sénégal. Livraison rapide avec Abavie.',
  },
  '/plans': {
    title: 'ABAWI Premium — Abonnements & Tarifs',
    desc:  'Choisissez votre plan ABAWI Premium : accès illimité aux guides, outils IA et académie pour entrepreneurs africains.',
  },
  '/a-propos': {
    title: 'À Propos — ABAWI | Portail Business Afrique',
    desc:  'Découvrez l\'histoire, la vision et l\'équipe ABAWI. Notre mission : démocratiser l\'excellence business pour l\'Afrique.',
  },

  // ── Outils — page liste ───────────────────────────────────────────────────
  '/outils': {
    title: 'Outils ABAWI — 30+ Applications Pro & IA Gratuites',
    desc:  'La boîte à outils premium pour l\'Afrique : CV, factures, business plan, studio photo/audio, IA, santé, emploi et plus encore.',
  },

  // ── Outils Professionnels ─────────────────────────────────────────────────
  '/outils/cv': {
    title: 'CV Creator ABAWI — Créez votre CV Professionnel en 5 min',
    desc:  'Générez un CV percutant avec 20+ templates premium adaptés au marché africain. Export PDF, ATS-compatible, 100% gratuit.',
  },
  '/outils/lettre': {
    title: 'Lettre de Motivation IA — ABAWI',
    desc:  'Rédigez une lettre de motivation convaincante avec l\'IA ABAWI. Adapté au Sénégal, UEMOA et marchés africains.',
  },
  '/outils/business-plan': {
    title: 'Business Plan Elite — Créez votre Plan d\'Affaires | ABAWI',
    desc:  'Construisez un business plan complet et bankable avec l\'IA ABAWI : étude de marché, projections financières SYSCOHADA, conformité OHADA.',
  },
  '/outils/pitch': {
    title: 'Pitch Deck Elite — Présentations Investisseurs | ABAWI',
    desc:  'Créez des présentations investisseurs de qualité supérieure : slides structurées, storytelling, design pro en quelques minutes.',
  },
  '/outils/facture': {
    title: 'Facture Creator — Documents Professionnels ABAWI',
    desc:  '50+ templates de factures, devis, bons de commande et avoirs. TVA, multi-devises, logo personnalisé, export PDF haute qualité.',
  },
  '/outils/analyse-cv': {
    title: 'Analyse CV IA — Score ATS & Optimisation | ABAWI',
    desc:  'Analysez votre CV avec l\'IA ABAWI : score ATS, points d\'amélioration, optimisation pour le marché africain. Gratuit et instantané.',
  },
  '/outils/finance': {
    title: 'Finance Elite — Gestion Financière pour PME Africaines | ABAWI',
    desc:  'Outil financier avancé : tableaux de bord, projections, analyses de rentabilité et gestion de trésorerie pour entreprises africaines.',
  },
  '/outils/juridique': {
    title: 'Juridique Elite — Contrats & Documents OHADA | ABAWI',
    desc:  'Vos documents juridiques en quelques clics : contrats, CGV, statuts, baux — conformes OHADA et droit sénégalais.',
  },
  '/outils/comptable': {
    title: 'Comptable Elite — SYSCOHADA & Fiscalité Sénégal | ABAWI',
    desc:  'Gestion comptable intelligente : SYSCOHADA, bilan, compte de résultat, déclarations fiscales Sénégal. Simple et fiable.',
  },
  '/outils/rh': {
    title: 'RH Elite — Paie & Contrats de Travail Sénégal | ABAWI',
    desc:  'Gestion RH complète : fiches de paie, contrats de travail, bulletins conformes au code du travail sénégalais.',
  },
  '/outils/immobilier': {
    title: 'Immobilier Elite — Estimation & Contrats Sénégal | ABAWI',
    desc:  'Outils immobiliers complets : estimation, contrats de vente/location, documents notariaux adaptés au marché sénégalais.',
  },
  '/outils/consultant': {
    title: 'Consultant Elite — Propositions & Rapports Pro | ABAWI',
    desc:  'Outils de consulting premium : propositions commerciales, rapports, cahiers des charges et plans d\'action professionnels.',
  },

  // ── Outils Créatifs ───────────────────────────────────────────────────────
  '/outils/infographie-pro': {
    title: 'Infographie Pro — Créateur Visuel Africain | ABAWI',
    desc:  'Créez des infographies professionnelles en quelques minutes : 100+ templates, export HD, adapté aux réseaux sociaux africains.',
  },
  '/outils/photo-studio-pro': {
    title: 'Photo Studio Pro — Retouche & Fond IA | ABAWI',
    desc:  'Studio photo professionnel dans votre navigateur : suppression de fond IA, photos ID conformes, retouches avancées, export HD.',
  },
  '/outils/audio-studio-elite': {
    title: 'Audio Studio Elite — Production Audio Professionnelle | ABAWI',
    desc:  'Studio audio complet : enregistrement, effets, compression, export MP3 192kbps, transcription IA Whisper et mesure LUFS.',
  },
  '/outils/studio-visuel-pro': {
    title: 'Studio Visuel Pro — Créateur Graphique | ABAWI',
    desc:  'Créez des visuels premium : bannières, posts réseaux sociaux, affiches — 22 templates professionnels, export PNG/JPEG.',
  },
  '/outils/image-pro': {
    title: 'Image Pro — Retouche IA & Conversion | ABAWI',
    desc:  'Retouche d\'images professionnelle dans le navigateur : filtres, redimensionnement, suppression de fond IA, conversion de format.',
  },
  '/outils/qr-code-pro': {
    title: 'QR Code Pro — Générateur Personnalisé | ABAWI',
    desc:  'Générez des QR codes personnalisés avec logo, couleurs et styles : vCards, liens, WiFi, paiements — export haute résolution.',
  },
  '/outils/pro-card-elite': {
    title: 'Pro Card Elite — Carte de Visite Numérique | ABAWI',
    desc:  'Créez votre carte de visite numérique professionnelle : design premium, partage QR code, contact instantané sans papier.',
  },
  '/outils/format-converter': {
    title: 'Format Converter — Conversion de Fichiers en Ligne | ABAWI',
    desc:  'Convertissez vos fichiers en ligne : PDF, images, audio, documents — rapide, gratuit et sans logiciel à installer.',
  },

  // ── Outils Linguistiques ──────────────────────────────────────────────────
  '/outils/dictionnaire-elite': {
    title: 'Dictionnaire Elite — Français & Terminologie Afrique | ABAWI',
    desc:  'Dictionnaire enrichi pour l\'Afrique : définitions, exemples, terminologie juridique, économique et médicale multilingue.',
  },
  '/outils/translator-elite': {
    title: 'Translator Elite — Traduction IA 50+ Langues | ABAWI',
    desc:  'Traduction IA haute précision : 50+ langues, terminologie professionnelle, langues africaines (Wolof, Bambara, Haoussa...).',
  },

  // ── Outils IA ─────────────────────────────────────────────────────────────
  '/outils/abawi-ia': {
    title: 'ABAWI IA — Votre Assistant Intelligence Artificielle Africain',
    desc:  'Assistant IA africain tout-en-un : recherches, analyses, rédaction, conseils business et réponses en temps réel.',
  },
  '/outils/exegetika': {
    title: 'ABAWI Exégetika — Analyse & Décryptage de Documents IA',
    desc:  'Analysez et décryptez tout document, rapport ou texte complexe avec l\'IA ABAWI. Synthèses rapides et précises.',
  },

  // ── Santé ─────────────────────────────────────────────────────────────────
  '/outils/sante': {
    title: 'Abavie — Plateforme Santé & Bien-être Sénégal | ABAWI',
    desc:  'Annuaire santé complet : hôpitaux, cliniques, pharmacies de garde, médecins. Carte interactive, urgences et IA santé. Sénégal.',
  },
  '/abavie': {
    title: 'Abavie — Santé & Bien-être au Sénégal | ABAWI',
    desc:  'Trouvez un médecin, une pharmacie de garde ou un hôpital au Sénégal. Carte interactive, éducation médicale et boutique santé.',
  },

  // ── Géo & Local ──────────────────────────────────────────────────────────
  '/outils/abspacegps': {
    title: 'AbSpace GPS — Géolocalisation & Analyse IA de Zone | ABAWI',
    desc:  'Localisez-vous précisément au Sénégal : quartier, adresse, commerces proches et analyse IA complète de votre zone en temps réel.',
  },
  '/outils/abzone': {
    title: 'AbZone — Forum Local & Communautés Sénégal | ABAWI',
    desc:  'Explorez et échangez autour des zones et quartiers du Sénégal : forum communautaire, informations locales, ressources de proximité.',
  },

  // ── Business & Communauté ─────────────────────────────────────────────────
  '/outils/maxavis': {
    title: 'MaxAvis Elite — Sondages & Collecte d\'Avis Professionnels | ABAWI',
    desc:  'Créez des sondages professionnels, collectez des avis clients et analysez les résultats avec des visualisations avancées.',
  },
  '/outils/tontine': {
    title: 'Tontine ABAWI — Gestion d\'Épargne Collective Numérique',
    desc:  'Gérez votre tontine facilement : suivi des cotisations, tour de table, historique et notifications pour tous les membres.',
  },
  '/outils/autoroute': {
    title: 'ABAWI AutoRoute — Navigation & Itinéraires au Sénégal',
    desc:  'Planifiez vos itinéraires au Sénégal : routes, distances, temps de trajet et points d\'intérêt sur carte interactive.',
  },
  '/outils/editeur-pro': {
    title: 'Éditeur Pro — Traitement de Texte Professionnel | ABAWI',
    desc:  'Éditeur de texte professionnel dans le navigateur : formatage avancé, modèles, export PDF et Word — sans logiciel.',
  },
  '/outils/smart-word-editor': {
    title: 'Smart Word Editor — Rédaction Intelligente | ABAWI',
    desc:  'Rédigez vos documents professionnels avec l\'éditeur intelligent ABAWI : IA intégrée, modèles et export multi-formats.',
  },
  '/outils/smart-office': {
    title: 'Smart Office — Suite Bureautique Cloud | ABAWI',
    desc:  'Suite bureautique complète dans le cloud : documents, présentations, tableurs et collaboration en temps réel pour équipes africaines.',
  },

  // ── Emploi & RH ───────────────────────────────────────────────────────────
  '/outils/recrute-moi-sn': {
    title: 'Recrute-moi SN — Offres d\'Emploi Sénégal | ABAWI',
    desc:  'Les meilleures offres d\'emploi au Sénégal : CDI, CDD, freelance, stages. Postulez directement et boostez votre carrière.',
  },
  '/outils/place-ouvrier': {
    title: 'Place Ouvrier — Trouvez un Ouvrier Qualifié au Sénégal | ABAWI',
    desc:  'Trouvez un ouvrier qualifié au Sénégal : maçon, plombier, électricien, menuisier, peintre — vérifiés et géolocalisés.',
  },
  '/outils/espace-ouvrier': {
    title: 'Espace Ouvrier — Publiez votre Profil de Professionnel | ABAWI',
    desc:  'Publiez votre profil d\'ouvrier qualifié et trouvez des chantiers près de chez vous au Sénégal avec ABAWI.',
  },

  // ── ABAWI 360 ─────────────────────────────────────────────────────────────
  '/abawi360': {
    title: 'ABAWI 360 — Suite de Gestion d\'Entreprise Complète',
    desc:  'ERP africain tout-en-un : CRM, comptabilité, RH, marketing, planification et statistiques pour PME et ETI sénégalaises.',
  },
  '/abawi360/crm': {
    title: 'CRM ABAWI 360 — Gestion Clients & Pipeline de Vente',
    desc:  'Gérez vos clients, prospects et pipeline de vente avec le CRM ABAWI 360. Suivi, relances et tableaux de bord en temps réel.',
  },
  '/abawi360/planification': {
    title: 'Planification ABAWI 360 — Gestion de Projets & Équipes',
    desc:  'Planifiez et suivez vos projets avec ABAWI 360 : tâches, jalons, équipes et rapports d\'avancement pour PME africaines.',
  },
  '/abawi360/statistiques': {
    title: 'Statistiques ABAWI 360 — Tableaux de Bord KPIs Business',
    desc:  'Visualisez vos indicateurs clés avec ABAWI 360 : ventes, revenus, clients, performance — tableaux de bord en temps réel.',
  },
  '/abawi360/marketing': {
    title: 'Marketing ABAWI 360 — Stratégie & Gestion de Campagnes',
    desc:  'Gérez vos campagnes marketing avec ABAWI 360 : emails, SMS, réseaux sociaux et analytics pour entreprises africaines.',
  },

  // ── Produits & Services ───────────────────────────────────────────────────
  '/abawi-pay': {
    title: 'ABAWI Pay — Solution de Paiement Mobile Sénégal',
    desc:  'Solution de paiement mobile pour le Sénégal : Orange Money, Wave, Free Money — intégration simple, rapide et sécurisée.',
  },
  '/abawi-bank': {
    title: 'ABAWI Bank — Services Financiers Digitaux pour l\'Afrique',
    desc:  'Services bancaires digitaux pour l\'Afrique : épargne, transferts, microfinance et gestion financière avec ABAWI.',
  },
  '/arkel-up-center': {
    title: 'ArkelUp Center — Imprimantes & Matériel Informatique Sénégal',
    desc:  'Matériel informatique et imprimantes professionnelles au Sénégal : HP, Dell, Lenovo, Canon — livraison, installation et SAV.',
  },
  '/abtalk': {
    title: 'AbTalk — La messagerie qui s\'adapte | ABAWI',
    desc:  'AbTalk, la messagerie intelligente de l\'écosystème ABAWI : discussions sécurisées, appels, partage de fichiers et recherche globale.',
  },
}

// ─── Handler ──────────────────────────────────────────────────────────────────

export default async function handler(request, context) {
  const url  = new URL(request.url)
  const path = url.pathname

  let meta     = null
  let imageUrl = ROUTE_IMAGE[path] ?? null  // per-route banner; dynamic routes may override below
  let ogType   = 'website'

  // 1 — Exact static match
  meta = STATIC[path] ?? null

  // 2 — Dynamic route detection (only if no static match)
  if (!meta) {
    const newsM     = path.match(/^\/news\/(.+)$/)
    const packM     = path.match(/^\/digital\/pack\/(.+)$/)
    const guideM    = path.match(/^\/digital\/(?!pack\/)(.+)$/)
    const fascM     = path.match(/^\/academy\/(.+)$/)
    const podcastM  = path.match(/^\/podcasts\/(.+)$/)
    const storeM    = path.match(/^\/store\/(.+)$/)
    const santeM    = path.match(/^\/boutique-sante\/(.+)$/)
    const maxavisM  = path.match(/^\/maxavis\/(.+)$/)

    if (newsM) {
      const fetched = await fetchNewsMeta(newsM[1])
      if (fetched) {
        meta     = fetched
        imageUrl = fetched.image || '/og/news.webp'
        ogType   = fetched.type  || 'article'
      } else {
        meta = {
          title: `${slugToReadable(newsM[1])} — ABAWI Actualités`,
          desc:  'Actualité économique et business en Afrique de l\'Ouest — ABAWI, votre portail d\'information premium.',
        }
        ogType = 'article'
      }
    } else if (packM) {
      meta = resolvePackMeta(packM[1])
    } else if (guideM) {
      meta = resolveGuideMeta(guideM[1])
    } else if (fascM) {
      meta = resolveAcademyMeta(fascM[1])
    } else if (podcastM) {
      meta = resolvePodcastMeta(podcastM[1])
    } else if (storeM) {
      meta = resolveStoreMeta()
    } else if (santeM) {
      meta = resolveSanteMeta()
    } else if (maxavisM) {
      const fetched = await fetchMaxAvisMeta(maxavisM[1])
      meta = fetched ?? {
        title: 'Sondage ABAWI — Donnez votre avis',
        desc:  'Participez à ce sondage ABAWI et partagez votre opinion. Rapide, simple et anonyme.',
      }
    }
  }

  if (!meta) return context.next()

  const response = await context.next()
  if (!response.ok) return response

  let html = await response.text()

  const ogImg   = esc(imageUrl
    ? (imageUrl.startsWith('http') ? imageUrl : `${url.origin}${imageUrl}`)
    : `${url.origin}${OG_IMAGE_PNG}`)
  const titre   = esc(meta.title)
  const desc    = esc(String(meta.desc ?? '').slice(0, 200))
  const pageUrl = esc(`${url.origin}${url.pathname}`)

  html = html
    // Title & description
    .replace(/<title>[^<]*<\/title>/, `<title>${titre}</title>`)
    .replace(/<meta name="description"[^>]*>/, `<meta name="description" content="${desc}" />`)
    // Canonical URL
    .replace(/<link rel="canonical"[^>]*>/, `<link rel="canonical" href="${pageUrl}" />`)
    // OG tags
    .replace(/<meta property="og:title"[^>]*>/,       `<meta property="og:title" content="${titre}" />`)
    .replace(/<meta property="og:description"[^>]*>/, `<meta property="og:description" content="${desc}" />`)
    .replace(/<meta property="og:url"[^>]*>/,         `<meta property="og:url" content="${pageUrl}" />`)
    .replace(/<meta property="og:type"[^>]*>/,        `<meta property="og:type" content="${ogType}" />`)
    .replace(
      /<meta property="og:image"(?!:)[^>]*>/,
      `<meta property="og:image" content="${ogImg}" /><meta property="og:image:secure_url" content="${ogImg}" /><meta property="og:image:type" content="image/webp" />`
    )
    .replace(/<meta property="og:image:width"[^>]*>/,  `<meta property="og:image:width" content="1200" />`)
    .replace(/<meta property="og:image:height"[^>]*>/, `<meta property="og:image:height" content="630" />`)
    // Twitter / X
    .replace(/<meta name="twitter:title"[^>]*>/,       `<meta name="twitter:title" content="${titre}" />`)
    .replace(/<meta name="twitter:description"[^>]*>/, `<meta name="twitter:description" content="${desc}" />`)
    .replace(/<meta name="twitter:image"[^>]*>/,       `<meta name="twitter:image" content="${ogImg}" />`)

  return new Response(html, {
    status:  response.status,
    headers: {
      'content-type':  'text/html; charset=utf-8',
      'cache-control': 'no-cache, no-store',
    },
  })
}

// ─── Netlify Edge path config ─────────────────────────────────────────────────

export const config = {
  path: [
    // Root
    '/',
    // Main sections
    '/news', '/news/*',
    '/digital', '/digital/*',
    '/academy', '/academy/*',
    '/podcasts', '/podcasts/*',
    '/store', '/store/*',
    '/boutique-sante', '/boutique-sante/*',
    '/plans',
    '/a-propos',
    // MaxAvis public surveys
    '/maxavis/*',
    // Outils — list page
    '/outils',
    // Outils — individual tools
    '/outils/cv',
    '/outils/lettre',
    '/outils/business-plan',
    '/outils/pitch',
    '/outils/facture',
    '/outils/analyse-cv',
    '/outils/finance',
    '/outils/juridique',
    '/outils/comptable',
    '/outils/rh',
    '/outils/immobilier',
    '/outils/consultant',
    '/outils/infographie-pro',
    '/outils/photo-studio-pro',
    '/outils/audio-studio-elite',
    '/outils/studio-visuel-pro',
    '/outils/image-pro',
    '/outils/qr-code-pro',
    '/outils/pro-card-elite',
    '/outils/format-converter',
    '/outils/dictionnaire-elite',
    '/outils/translator-elite',
    '/outils/abawi-ia',
    '/outils/exegetika',
    '/outils/sante',
    '/outils/abspacegps',
    '/outils/abzone',
    '/outils/maxavis',
    '/outils/tontine',
    '/outils/autoroute',
    '/outils/editeur-pro',
    '/outils/smart-word-editor',
    '/outils/smart-office',
    '/outils/recrute-moi-sn',
    '/outils/place-ouvrier',
    '/outils/espace-ouvrier',
    // Santé
    '/abavie',
    // ABAWI 360
    '/abawi360',
    '/abawi360/crm',
    '/abawi360/planification',
    '/abawi360/statistiques',
    '/abawi360/marketing',
    // Products & services
    '/abawi-pay',
    '/abawi-bank',
    '/arkel-up-center',
    '/abtalk',
  ],
}
